import json,hashlib,itertools,ast
from pathlib import Path
from datetime import datetime,timezone,timedelta
root=Path('/Users/orderly_ray/Leader');o=root/'orchestration';p=o/'reports';tid='CP2-ASR-REVIEW-TOKEN-PROVENANCE-AUDIT-001'
def sha(b):return hashlib.sha256(b).hexdigest()
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
names={'CP2-ASR-REAL-COMMENT-CAPABILITY-REVIEW-001.json':'0d8b34a06960a2c82a07effc376b60efe3c06aea1c968fb5a83b160c0d0519e6','CP2-ASR-REAL-COMMENT-CAPABILITY-REVIEW-001-verification.json':'ca492d93813eb41dc589dbf868c49a8d423c8611d8ee180265c388ed3cf7c102','CP2-ASR-REAL-COMMENT-CAPABILITY-REVIEW-001-verify.py':'923d0669081f5ad7d2d6c35dace85c5c34b8ce3fbf5443a777f0292179fbe3e9','CP2-ASR-REAL-COMMENT-REVIEW-AUTHORIZATION-001.json':'c66a9fe77a77e15ca6dfa8f958f47ac1de4e1816de52779add3b9eee497163c7','CP2-ASR-REAL-COMMENT-REVIEW-AUTHORIZATION-001-approved.json':'df26a4884e47a63c3cdbd0e2afc118e4a4f70f4ef7db9a267d6307e01b4aa9c2'}
refs=[]
for n,h in names.items():
 b=(p/n).read_bytes();assert sha(b)==h;refs.append(dict(path=str(p/n),bytes=len(b),sha256=h))
r=json.loads((p/'CP2-ASR-REAL-COMMENT-CAPABILITY-REVIEW-001.json').read_bytes());v=json.loads((p/'CP2-ASR-REAL-COMMENT-CAPABILITY-REVIEW-001-verification.json').read_bytes());assert r['verification_report_sha256']==refs[1]['sha256'] and r['verification_script_sha256']==refs[2]['sha256']
s=(p/'CP2-ASR-REAL-COMMENT-CAPABILITY-REVIEW-001-verify.py').read_text();ast.parse(s)
assert "hit=segment.lower().index(b'websocket')" in s.splitlines()[22] and "segment.lower().count(b'websocket')==1" in s.splitlines()[22]
for a,b in zip(r['targets'],v['targets']):
 assert 'raw_token' not in a and 'token' not in a and 'raw_token' not in b and 'token' not in b
 for k in ('line','line_sha256','physical_line_sha256','line_byte_start','line_byte_end','token_byte_start','token_byte_end','rule'):assert a[k]==b[k]
variants=[''.join(chars).encode() for chars in itertools.product(*[(c,c.upper()) for c in 'websocket'])];assert len(set(variants))==512 and all(x.lower().index(b'websocket')==0 and x.lower().count(b'websocket')==1 and len(x)==9 for x in variants)
now=datetime.now(timezone(timedelta(hours=8))).isoformat();report={'task_id':tid,'RESULT':'INSUFFICIENT_DERIVED_EVIDENCE','reviewed_at':now,'source_references':refs,'static_script_audit':{'script_not_executed_or_imported':True,'line23':'segment.lower().index/count finds case-insensitive literal; no original token extraction or recorded raw_token','line24':'records interval and rule, no original token bytes','line25':'writes verification report subsequently pinned by original R','conclusion':'Historical script/results do not recover exact original token case. Neither normalized rule nor chat summary can substitute for original bytes.'},'authored_semantics_probe':{'case_variants':512,'all_have_same_lowercase_match_and_length':True,'claim_limit':'Demonstrates noninjective matching only; not asserting variants have equal body/line hashes or are actual source.'},'affected_targets':[{k:t[k] for k in ('line','line_sha256','physical_line_sha256','line_byte_start','line_byte_end','token_byte_start','token_byte_end','rule')} for t in r['targets']],'authorization_distinction':'Original approved offline review names this exact retained envelope/header and two hits. Its written scope does not specify a once-only read; prohibition on old acquisition authority concerns acquisition. Current K task and formal derived-only stage still do not allow private-body access. Ask PM to decide a separate exact evidence-completion task under persistent existing scope, without inventing new acquisition authority or automatic user-confirmation gate.','candidate_unchanged':'1fe85740a185a63ca4f35df2abd22ae410f82fbb','real_body_reads_this_audit':0,'network_calls':0,'operational_effect':{'K_created':False,'original_R_modified':False,'pending_cleared':False,'new_acquisition_authorized':False},'next':'PRODUCT_DECISION_REQUIRED: minimal exact-byte provenance completion for already-reviewed two occurrences, or PAUSE; do not weaken schema or rebuild candidate.'}
write(p/(tid+'-report.json'),report)
t=json.loads((o/'current-task.json').read_bytes());t.update(status='completed',completed_at=now);write(o/'tasks'/(tid+'-completed.json'),t);s=json.loads((o/'state.json').read_bytes());s.update(state='AWAITING_REVIEW',updated_at=now);write(o/'current-task.json',t);write(o/'state.json',s)
# Audit objective completed; result is evidence insufficiency, not K acceptance.
t.update(status='accepted',accepted_at=now,acceptance_scope='Read-only audit conclusion accepted; K remains blocked',report=str((p/(tid+'-report.json')).relative_to(root)),report_sha256=sha((p/(tid+'-report.json')).read_bytes()));write(o/'tasks'/(tid+'-accepted.json'),t);write(o/'current-task.json',t);s.update(state='ACCEPTED',last_accepted_task_id=tid);s['observations'].append('K raw_token provenance blocked; separate Leader static audit of pinned historical firstparty verifier confirms lowercased matching and no rawtoken field. No privatebody read, originalR/C unchanged. PM minimal evidence-completion decision next.');write(o/'state.json',s)
print(json.dumps({'report':str(p/(tid+'-report.json')),'sha256':sha((p/(tid+'-report.json')).read_bytes())}))
